import assert from 'node:assert/strict';
import {fbInsertionPlan} from '../fb-insertion.js';
const block={name:'Timer',kind:'FUNCTION_BLOCK',hidden:false,evidence_kind:'installed-declared-block-interface',pins:[{name:'IN',type:'BOOL',direction:'input'},{name:'Q',type:'BOOL',direction:'output'},{name:'State',type:'TIME',direction:'in_out'}]};
const read={language:'ST',body:'(* Before *)\nRETURN;\n',variables:[{name:'Done',type:'BOOL'},{name:'Accum',type:'TIME'},{name:'Wrong',type:'INT'}]};
const args={baseline_saved:true,expected_body:read.body,instance:'NewTimer',offset:13,bindings:{in:'FALSE',Q:'Done',State:'Accum'}};
const plan=fbInsertionPlan(args,block,read);
assert.equal(plan.declaration.type,'Timer');
assert.equal(plan.declaration.address,null);
assert.equal(plan.declaration.initial_value,null);
assert.equal(plan.declaration.description,null);
assert.equal(plan.call,'NewTimer(IN := FALSE, State := Accum);\r\nDone := NewTimer.Q;\r\n');
assert.ok(plan.code.endsWith('RETURN;\n'));
assert.throws(()=>fbInsertionPlan({...args,expected_body:'stale'},block,read));
for(const bindings of [{IN:'FALSE',Q:'Wrong',State:'Accum'},{IN:'FALSE',Q:'Done'}, {Unknown:'0',State:'Accum'},{IN:'FALSE); RETURN;',State:'Accum'},{IN:'FALSE, Q => Done',State:'Accum'},{IN:'FALSE',in:'TRUE',State:'Accum'},{State:'Missing'}])assert.throws(()=>fbInsertionPlan({...args,bindings},block,read));
assert.throws(()=>fbInsertionPlan({...args,instance:'Done'},block,read));
assert.throws(()=>fbInsertionPlan(args,{...block,hidden:true},read));
assert.throws(()=>fbInsertionPlan({...args,offset:1},block,read));
const commentRead={...read,body:'(* open\ncomment *)\n'};
assert.throws(()=>fbInsertionPlan({...args,expected_body:commentRead.body,offset:8},block,commentRead));
const stringBlock={...block,pins:[{name:'Text',type:'STRING',direction:'input'}]};
assert.ok(fbInsertionPlan({...args,bindings:{Text:"CONCAT('a; b', 'c')"}},stringBlock,read).call.includes("CONCAT('a; b', 'c')"));
console.log('FB declared-direction wiring, direct-variable types, in-out requirements, stale bodies, collisions, safe expressions and insertion boundaries passed');
