import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { apply } from '../index.js';
const read = p => readFileSync(new URL('../' + p, import.meta.url), 'utf8');
const tools = new Map();
apply({ get: () => undefined, tools: { register: t => tools.set(t.name, t) }, on() {} });
const guide = await tools.get('mw_ide_edit_guide').execute({ operation: 'engineering' });
assert.deepEqual(Object.keys(guide).sort(), ['mode', 'operation', 'steps', 'action_performed', 'engineering_guidance'].sort());
assert.equal(guide.engineering_guidance, read('docs/ENGINEERING_WORKFLOW.md'));
assert.equal(guide.action_performed, false);
assert.equal(guide.mode, 'ide-first');
assert.ok(guide.steps.every(s => typeof s === 'string'));
assert.match(guide.steps.join(' '), /ENGINEERING_WORKFLOW/);
const variables = await tools.get('mw_ide_edit_guide').execute({operation:'variables'});
assert.equal(variables.variable_guidance, read('docs/VARIABLE_WORKSHEET_WORKFLOW.md'));
assert.equal(variables.action_performed, false);
assert.match(variables.steps.join(' '), /group row.*NOT variable data/);
assert.match(variables.steps.join(' '), /mw_code_verify_variables/);
const skill = read('SKILL.md'), engineering = read('docs/ENGINEERING_WORKFLOW.md');
assert.match(skill, /read `docs\/ENGINEERING_WORKFLOW.md`/);
for (const section of ['Tasks and function blocks', 'Axis coordinates and cams', 'Registration and continuous processes', 'PLC authority and IO contract', 'Stops, home and recovery', 'Behavioral acceptance matrix', 'Sources and version limits']) assert.ok(engineering.includes('## ' + section), section);
for (const caveat of ['Judgment', 'login', '0.01', '60 ft/min', 'three sheets', 'never label proposed tests passed']) assert.ok(engineering.includes(caveat), caveat);
const programming = read('docs/PROGRAMMING_KNOWLEDGE.md');
assert.doesNotMatch(programming, /commit through the existing transactional writer/);
assert.match(read('docs/NATIVE_EDIT_WORKFLOW.md'), /Superseded by IDE_FIRST_WORKFLOW/);
assert.match(read('docs/VERIFICATION_2026-09-30.md'), /HISTORICAL ONLY/);
for (const tool of tools.values()) assert.doesNotMatch(tool.description, /mw_code_pou_create|close IDE -> edit the stage|Required before writing code/, tool.name);
assert.ok(JSON.parse(read('package.json')).files.includes('verification.js'));
const contributing = read('CONTRIBUTING.md');
assert.match(contributing, /separately connected computer-use MCP/);
assert.doesNotMatch(contributing, /CFB container writer\s+for code|only transplant from a known-good donor/);
const readme = read('README.md');
for (const section of ['Requirements and installation', 'First use: open IDE or a new test copy', 'Capabilities and evidence', 'Troubleshooting and support']) assert.ok(readme.includes('## ' + section), section);
for (const doc of ['CONTRIBUTING.md', 'CHANGELOG.md']) assert.ok(JSON.parse(read('package.json')).files.includes(doc), doc);
console.log('Engineering guide delivery, schema-shaped result, source limits and active instruction routing passed');
