import assert from 'node:assert/strict';
import {structurePlan,nativeStructureChange} from '../native-structure.js';
const meta={name:'Main',type:'PROGRAM',language:2,plc_type:'',processor_type:'',read_only:false};
const pou={name:'Main',type:'PROGRAM',language:'ST',return_type:'',body_sha256:'body',body_blank:false,variables:[],identifiers:[],reference_scan_complete:true};
const task={name:'Cyclic',kind:'CYCLIC',instances:[],settings:{TYPE:'CYCLIC',INTERVAL:'T#100ms',PRIORITY:'0',WATCHDOG:'100',WATCHDOG_DISPLAY:'',WATCHDOG_ENABLED:'YES'}};
const before={pous:[pou],tasks:[task],globals:[],program_sources:{'POE/Main/src.st1':{'Main.STB':'body'}},file_hashes:{'LIST.POU':'hash'}};
const live={pous:[meta],tasks:[{name:task.name,kind:task.kind,instances:[]}]};
const args={operation:'create',name:'NewPou',baseline_saved:true};
const plan=(scope,input,saved=before,native=live)=>structurePlan(scope,input,structuredClone(saved),structuredClone(native));
assert.equal(plan('pou',args).native.pous.length,2);
assert.throws(()=>plan('pou',{...args,name:'Main'}),/exists/);
assert.throws(()=>plan('pou',{...args,name:'A'.repeat(31)}),/Invalid/);
assert.throws(()=>plan('pou',{operation:'create',name:'Fn',pou_type:'FUNCTION'}),/return type/);
assert.throws(()=>plan('pou',{operation:'delete',name:'Main'}),/approval/);
assert.throws(()=>plan('pou',{operation:'rename',name:'Main',new_name:'Renamed'}),/review/);
const referenced={...before,pous:[pou,{...pou,name:'Caller',identifiers:['MAIN']}]};
assert.throws(()=>plan('pou',{operation:'delete',name:'Main',references_reviewed:true,user_approved:true},referenced),/references/);
const assigned={...before,tasks:[{...task,instances:[{name:'DifferentInstance',type:'Main'}]}]};
assert.throws(()=>plan('pou',{operation:'delete',name:'Main',references_reviewed:true,user_approved:true},assigned),/assignment/);
const taskArgs={operation:'edit',name:'Cyclic',settings_changes:{INTERVAL:'T#20ms',PRIORITY:'5'}};
const edited=plan('task',taskArgs);
assert.equal(edited.settings.WATCHDOG_DISPLAY,'');
assert.equal(edited.settings.WATCHDOG,'100');
assert.equal(edited.settings.INTERVAL,'T#20ms');
for(const changes of [{INTERVAL:'T#0ms'},{INTERVAL:'T#20ms\nOTHER := NO'},{PRIORITY:'-1'},{UNKNOWN:'1'},{WATCHDOG_ENABLED:'MAYBE'}])
  assert.throws(()=>plan('task',{...taskArgs,settings_changes:changes}));
assert.throws(()=>plan('task',{operation:'create',name:'EightChr'}),/Invalid/);
assert.throws(()=>plan('task',{operation:'delete',name:'Cyclic',user_approved:true},assigned,{...live,tasks:[{...live.tasks[0],instances:assigned.tasks[0].instances}]}),/Unassign/);
const instance=plan('task',{operation:'assign',name:'Cyclic',pou:'Main',instance:'DifferentInstance'});
assert.deepEqual(instance.native.tasks[0].instances,[{name:'DifferentInstance',type:'Main'}]);
const removed=plan('task',{operation:'unassign',name:'Cyclic',instance:'DifferentInstance',user_approved:true},assigned,instance.native);
assert.equal(removed.native.tasks[0].instances.length,0);
let mutations=0,reads=0;
const deps={status:async()=>({is_modified:false}),saved:async()=>reads++?{...before,pous:[pou,{...pou,name:'NewPou',body_blank:true,body_sha256:'empty'}]}:before,
  snapshot:async()=>live,mutate:async req=>{mutations++;assert.deepEqual(req.before_files,before.file_hashes);return {saved:true,is_modified:false,snapshot:req.expected_native};}};
assert.equal((await nativeStructureChange('pou',args,deps)).verification.accepted,true);
await assert.rejects(()=>nativeStructureChange('pou',{...args,baseline_saved:false},deps),/save/);
await assert.rejects(()=>nativeStructureChange('pou',args,{...deps,status:async()=>({is_modified:true})}),/save/);
reads=0;
await assert.rejects(()=>nativeStructureChange('pou',args,{...deps,snapshot:async()=>({...live,pous:[]})}),/disagree/);
assert.equal(mutations,1);
reads=0;
const damaged=await nativeStructureChange('pou',args,{...deps,saved:async()=>reads++?{...before,pous:[{...pou,body_sha256:'damaged'},{...pou,name:'NewPou',body_blank:true}]}:before});
assert.equal(damaged.verification.accepted,false);
assert.ok(damaged.verification.errors.some(e=>e.includes('Unrelated POU')));
for(const translationFiles of [ {'POE/Main/Translation.xml':'changed'}, {}, {'POE/Main/Translation.xml':'original','POE/Main/ExtraTranslation.xml':'added'} ]){
  reads=0;
  const baseline={...before,translation_files:{'POE/Main/Translation.xml':'original'}};
  const changed=await nativeStructureChange('pou',args,{...deps,saved:async()=>reads++?{...baseline,pous:[pou,{...pou,name:'NewPou',body_blank:true}],translation_files:translationFiles}:baseline});
  assert.equal(changed.verification.accepted,false);
  assert.ok(changed.verification.errors.some(e=>e.includes('Unrelated translation')));
}
reads=0;
const extraSource=await nativeStructureChange('pou',args,{...deps,saved:async()=>reads++?{...before,pous:[pou,{...pou,name:'NewPou',body_blank:true}],program_sources:{...before.program_sources,'POE/Main/extra.st1':{Extra:'added'}}}:before});
assert.equal(extraSource.verification.accepted,false);
assert.ok(extraSource.verification.errors.some(e=>e.includes('Unrelated program streams')));
let retained;
reads=0;
await assert.rejects(()=>nativeStructureChange('pou',args,{...deps,
  retainPlan:async record=>{retained=record;},mutate:async()=>{assert.ok(retained);throw Error('native save stalled');}}),/save stalled/);
assert.deepEqual(retained.baseline,before);
assert.equal(retained.expected_native.pous.length,2);
console.log('Native structure consent, reference/type/instance checks, task field preservation, drift and collateral source guards passed');
